apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app.kubernetes.io/name: it-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
    spec:
      containers:
      - name: it-tools
        image: ghcr.io/sharevb/it-tools:nightly@sha256:4b7f532f8e322bed4378fd8e62945471ab846acf22c5e22e302a4b0b2c429457
        env: 
        - name: TZ
          value: America/Detroit
        ports:
        - name: http
          containerPort: 8080
